#include "MOTOR_interface.h"


void HALL_MOTOR_CCW(MOTOR_type motor)
{
	MCAL_DIO_u8_SetPinValue(PORT_MOTOR,PIN1_MOTOR1,PIN_LOW);
	MCAL_DIO_u8_SetPinValue(PORT_MOTOR,PIN2_MOTOR1,PIN_HIGH);
}
void HALL_MOTOR_CW(MOTOR_type motor)
{
	MCAL_DIO_u8_SetPinValue(PORT_MOTOR,PIN1_MOTOR1,PIN_HIGH);
	MCAL_DIO_u8_SetPinValue(PORT_MOTOR,PIN2_MOTOR1,PIN_LOW);
}
void HALL_MOTOR_stop(MOTOR_type motor)
{
	MCAL_DIO_u8_SetPinValue(PORT_MOTOR,PIN1_MOTOR1,PIN_LOW);
	MCAL_DIO_u8_SetPinValue(PORT_MOTOR,PIN2_MOTOR1,PIN_LOW);

}
